import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import '@mantine/core/styles.css';
import "../styles/globals.scss";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import {mantineHtmlProps, MantineProvider} from "@mantine/core";
import { ColorSchemeScript } from '@mantine/core';
import {theme} from "@/styles/theme";
import {CartProvider} from "@/context/CoffeeContext";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" {...mantineHtmlProps}>
            <head>
                <ColorSchemeScript/>
                <title>Coffee</title>
            </head>
            <body className={`${geistSans.variable} ${geistMono.variable}`}>
                <MantineProvider theme={theme}>
                    <CartProvider>
                        <Header/>
                        {children}
                        <Footer/>
                    </CartProvider>
                </MantineProvider>
            </body>
        </html>
    );
}
